version: '3.5'

networks:
  localdev:
    name: localdev

services:
  main-api:
    build: ./Tweetbook
    restart: always
    ports:
      - "7000:80"
    depends_on:
      - db-server
      - redis
    networks:
      - localdev

  db-server:
    image: postgres:latest
    container_name: db-server
    environment:
      POSTGRES_DB: tweetbook
      POSTGRES_USER: ilee
      POSTGRES_PASSWORD: my_password
    ports:
      - "5433:5432"
    networks:
      - localdev
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - localdev
